package com.chatty.android.chattyClient.constants;

public class ActionType {
  public final static String REQUEST_GET_DIARIES = "REQUEST_GET_DIARIES";
  public final static String REQUEST_GET_DIARIES_ERROR = "REQUEST_GET_DIARIES_ERROR";
  public final static String REQUEST_GET_DIARIES_SUCCESS = "REQUEST_GET_DIARIES_SUCCESS";

  public final static String REQUEST_GET_PARTNER_PROFILE_DETAIL = "REQUEST_GET_PARTNER_PROFILE_DETAIL";
  public final static String REQUEST_GET_PARTNER_PROFILE_DETAIL_ERROR = "REQUEST_GET_PARTNER_PROFILE_DETAIL_ERROR";
  public final static String REQUEST_GET_PARTNER_PROFILE_DETAIL_SUCCESS = "REQUEST_GET_PARTNER_PROFILE_DETAIL_SUCCESS";

  public final static String REQUEST_GET_DIARIES_DETAIL = " REQUEST_GET_DIARIES_DETAIL";
  public final static String REQUEST_GET_DIARIES_DETAIL_ERROR = " REQUEST_GET_DIARIES_DETAIL_ERROR";
  public final static String REQUEST_GET_DIARIES_DETAIL_SUCCESS = " REQUEST_GET_DIARIES_DETAIL_SUCCESS";
}
