package com.chatty.android.chattyClient.constants;

public class ActionType {
  public final static String REQUEST_ADD_FRIEND = "REQUEST_ADD_FRIEND";
  public final static String REQUEST_ADD_FRIEND_ERROR = "REQUEST_ADD_FRIEND_ERROR";
  public final static String REQUEST_ADD_FRIEND_SUCCESS = "REQUEST_ADD_FRIEND_SUCCESS";

  public final static String REQUEST_APPEND_CHAT = "REQUEST_APPEND_CHAT";
  public final static String REQUEST_APPEND_CHAT_ERROR = "REQUEST_APPEND_CHAT_ERROR";
  public final static String REQUEST_APPEND_CHAT_SUCCESS = "REQUEST_APPEND_CHAT_SUCCESS";

  public final static String REQUEST_GET_DIARIES = "REQUEST_GET_DIARIES";
  public final static String REQUEST_GET_DIARIES_ERROR = "REQUEST_GET_DIARIES_ERROR";
  public final static String REQUEST_GET_DIARIES_SUCCESS = "REQUEST_GET_DIARIES_SUCCESS";

  public final static String REQUEST_GET_FRIENDS_LIST = "REQUEST_GET_FRIENDS_LIST";
  public final static String REQUEST_GET_FRIENDS_LIST_ERROR = "REQUEST_GET_FRIENDS_LIST_ERROR";
  public final static String REQUEST_GET_FRIENDS_LIST_SUCCESS = "REQUEST_GET_FRIENDS_LIST_SUCCESS";

  public final static String REQUEST_GET_PARTNER_PROFILE_DETAIL = "REQUEST_GET_PARTNER_PROFILE_DETAIL";
  public final static String REQUEST_GET_PARTNER_PROFILE_DETAIL_ERROR = "REQUEST_GET_PARTNER_PROFILE_DETAIL_ERROR";
  public final static String REQUEST_GET_PARTNER_PROFILE_DETAIL_SUCCESS = "REQUEST_GET_PARTNER_PROFILE_DETAIL_SUCCESS";

  public final static String REQUEST_GET_DIARIES_DETAIL = "REQUEST_GET_DIARIES_DETAIL";
  public final static String REQUEST_GET_DIARIES_DETAIL_ERROR = "REQUEST_GET_DIARIES_DETAIL_ERROR";
  public final static String REQUEST_GET_DIARIES_DETAIL_SUCCESS = "REQUEST_GET_DIARIES_DETAIL_SUCCESS";

  public final static String REQUEST_START_CHAT = "REQUEST_START_CHAT";
  public final static String REQUEST_START_CHAT_ERROR = "REQUEST_START_CHAT_ERROR";
  public final static String REQUEST_START_CHAT_SUCCESS = "REQUEST_START_CHAT_SUCCESS";
}
